import langchain


def summarize_text(text, num_sentences=5):
    """
    Summarizes the input text using the `langchain` library.

    Args:
    - text (str): The input text to be summarized.
    - num_sentences (int): The number of sentences to include in the summary. Default value is 5.

    Returns:
    - str: A summary of the input text, generated by the `langchain` library.
    """
    summarizer = langchain.Summarizer('english')
    summary = summarizer.summarize(text, num_sentences=num_sentences)
    return summary
