from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lsa import LsaSummarizer
from sumy.summarizers.text_rank import TextRankSummarizer


def summarize_text(text, num_sentences=5, algorithm='lsa'):
    """
    Summarizes the input text using the Sumy library.

    Args:
    - text (str): The input text to be summarized.
    - num_sentences (int): The number of sentences to include in the summary. Default value is 5.
    - algorithm (str): The summarization algorithm to use. Valid options are 'lsa' and 'text-rank'. Default is 'lsa'.

    Returns:
    - str: A summary of the input text, generated by the Sumy library.
    """
    parser = PlaintextParser.from_string(text, Tokenizer('english'))
    if algorithm == 'lsa':
        summarizer = LsaSummarizer()
    elif algorithm == 'text-rank':
        summarizer = TextRankSummarizer()
    else:
        raise ValueError("Invalid algorithm specified. Valid options are 'lsa' and 'text-rank'.")
    summary = summarizer(parser.document, num_sentences)
    return ' '.join(str(sentence) for sentence in summary)
